<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pendaftar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pendaftar by id
     */
    function get_pendaftar($id)
    {
        return $this->db->get_where('tbl_pendaftar',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all pendaftars count
     */
    function get_all_pendaftars_count()
    {
        $this->db->from('tbl_pendaftar');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all pendaftars
     */
    function get_all_pendaftars($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_pendaftar')->result_array();
    }
        
    /*
     * function to add new pendaftar
     */
    function add_pendaftar($params)
    {
        $this->db->insert('tbl_pendaftar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pendaftar
     */
    function update_pendaftar($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_pendaftar',$params);
    }
    
    /*
     * function to delete pendaftar
     */
    function delete_pendaftar($id)
    {
        return $this->db->delete('tbl_pendaftar',array('id'=>$id));
    }
}
